<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <InvariantGlobalization>false</InvariantGlobalization>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Dapper" Version="2.1.79" />
    <PackageReference Include="dbup-mysql" Version="6.1.0" />
    <PackageReference Include="Discord.Net" Version="3.20.1" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.11" />
    <PackageReference Include="MySqlConnector" Version="2.6.2" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Migrations\*.sql" />
  </ItemGroup>

</Project>
